name: Sync to Hugging Face hub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push GitHub files to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git remote add space "https://adityap12:${HF_TOKEN}@huggingface.co/spaces/adityap12/OpenAI-chatbot-Query-app.git"

          git push space HEAD:main --force
